build:
  architectures:
    - amd64
    - aarch64
  variants:
    - tag: "7"
      containerfile: Containerfile.pkg
      args:
        JFFMPEG_PORT: jellyfin-ffmpeg7
      aliases: ["latest"]
      default: true
    - tag: "8"
      containerfile: Containerfile
      args:
        JFFMPEG_PORT: jellyfin-ffmpeg8

cit:
  mode: command
  command: ["-version"]
  expect_exit: 0
  expect_output: "ffmpeg version .*Jellyfin"
  puid: false
